import { Metadata } from "next";

export const homeMetadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "",
  authors: [],
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://example.com",
    siteName: "Create Next App",
    images: [
      {
        url: "https://example.com/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Create Next App",
      },
    ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      "index": true,
      "follow": true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};
